# Generated by Django 2.2.26 on 2022-01-11 20:16

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usersapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("da29a2bf-5879-470f-bc6f-005f06b125f1"), primary_key=True, serialize=False
            ),
        ),
    ]
