# Generated by Django 2.2.26 on 2022-01-11 20:19

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usersapp", "0002_auto_20220111_2316"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("e916574c-3433-456a-a5ef-bb6c3598c5b1"), primary_key=True, serialize=False
            ),
        ),
    ]
