# Generated by Django 2.2.26 on 2022-01-19 18:40

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usersapp", "0003_auto_20220111_2319"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("0708c730-4bb0-4de5-8b05-224b10b16c7f"), primary_key=True, serialize=False
            ),
        ),
    ]
