# Generated by Django 2.2.26 on 2022-01-19 18:51

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usersapp", "0004_auto_20220119_2140"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("11f1e857-bd6d-4b28-a5fd-7ce831b95002"), primary_key=True, serialize=False
            ),
        ),
    ]
